# Generated by Django 4.2.2 on 2023-06-12 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Knowledge',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=16, verbose_name='Login')),
                ('bucket', models.CharField(max_length=16, verbose_name='Bucket')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('content', models.TextField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
