# Generated by Django 4.2.2 on 2023-06-12 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledge',
            name='bucket',
            field=models.IntegerField(choices=[(0, 'COS'), (1, 'Deal Creation'), (2, 'Deal Support'), (3, 'Merchandising'), (4, 'CMBS'), (5, 'Instock'), (6, 'Ad-hoc'), (7, 'AMA')], default=0, verbose_name='Bucket'),
        ),
    ]
