# Generated by Django 4.2.2 on 2023-06-15 11:12

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0002_alter_knowledge_bucket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledge',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='Content'),
        ),
    ]
